version: '3'

services:
  data_base:
    container_name: data_base
    image: postegres: latest
    enviroment:
      postgres_db: data_northwind
      postegres_user: postgres
      postegres_pass: admin
    volumes:
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 55432:5432
    networks:
      - data_base

pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 5050:5050
    networks:
      - data_base    
